# Generated by Django 5.1.4 on 2025-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/')),
                ('glb_file1', models.FileField(blank=True, null=True, upload_to='glb_files/')),
                ('glb_file2', models.FileField(blank=True, null=True, upload_to='glb_files/')),
                ('glb_file3', models.FileField(blank=True, null=True, upload_to='glb_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
